import { MetadataRoute } from "next";
import { personalInfo } from "@/lib/tools-data";

/**
 * Robots.txt Configuration
 *
 * Tells search engine crawlers which pages they can access
 * This file is automatically generated by Next.js
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = `https://${personalInfo.domain}`;

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/", "/static/"],
      },
      {
        userAgent: "Googlebot",
        allow: "/",
      },
      {
        userAgent: "Bingbot",
        allow: "/",
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
